services:

  # config
  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    

  # Eureka  (media) 
  media:
    build: ./media
    container_name: media
    ports:
      - "8761:8761"
   
    networks:
      - microservices-net
    

  # PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  # user 
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      # overide application.proprties
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://media:8761/eureka/
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: "1111"
    networks:
      - microservices-net
   

  # gateway
  gateaway:
    build: ./gateaway
    container_name: gateaway
    ports:
      - "7001:7001"
  
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://media:8761/eureka/
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres-data:
